<a href="https://colab.research.google.com/github/GARCIAAA123/Introduction-to-Machine-Learning/blob/main/3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Machine Learning Chapter 3.1**
# **Multilayer Perceptron with Step function**
---

## Import libraries

In [ ]:
import numpy as np                  # for scientific computing (e.g. culclations with array)
import matplotlib.pyplot as plt     # for visualization

## **Example 3.1.1** Implementation of inner-product

In [ ]:
x = np.array([1, 0, 1])
w = np.array([[2],
              [3],
              [-1]])
b = -2
p = np.dot(x, w) + b
print(p)

[-1]


## **Example 3.1.2** Implementation of formal neuron model (1)

In [ ]:
x = np.array([1, 1, 0])
w = np.array([[0.5],
              [1.0],
              [0.5]])
b = -1

def formal_neuron(x, w, b):
    p = np.dot(x, w) + b
    y = p > 0
    return np.int64(y)  # cast from boolean to integer

y = formal_neuron(x, w, b)
print(y)

[1]


##**Example 3.1.3** Numpy broadcastiong

In [ ]:
a = np.array([1, 2, 3]) # matrix (vector)
b = 2 # scalar

print(a * b)

[2 4 6]


## **Example 3.1.4** Implementation of formal neuron model (2)

In [ ]:
x = np.array([[0,0,0],
              [0,0,1],
              [0,1,0],
              [0,1,1],
              [1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
w = np.array([[0.5],
              [1.0],
              [0.5]])
b = -1

def formal_neuron(x, w, b):
    p = np.dot(x, w) + b
    y = p > 0
    return np.int64(y)

y = formal_neuron(x, w, b)
print(y)

[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]]


## 🤔 **Exercise 3.1.1**

In [ ]:
x = [[1,0,1],
    [0,1,0],
    [1,1,1]]
w =[[0.6],
    [-1.5],
    [1.0]]
b = -1

def formal_neuron(x, w, b):
    p = np.dot(x, w) + b
    y = p > 0
    return np.int64(y)

y = formal_neuron(x, w, b)
print(y)

[[1]
 [0]
 [0]]


## **Example 3.1.5** Implementation of formal neuron model (3)

In [ ]:
x = np.array([[0,0,0],
              [0,0,1],
              [0,1,0],
              [0,1,1],
              [1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
w = np.array([[0.5, 0.0],
              [1.0, 0.5],
              [0.5, 1.0]])
b = np.array([-0.5, -1.0])

def formal_neuron(x, w, b):
    p = np.dot(x, w) + b
    y = p > 0
    return np.int64(y)

y = formal_neuron(x, w, b)
print(y)

## 🤔 **Exercise 3.1.2**

In [ ]:
x = [[1,0,1],
    [0,1,0],
    [1,1,1],
    [0,1,1]]
w =[[2,-1,3],
    [0,4,1],
    [-4,2,-2]]
b = [[-2,0, -1]]

def formal_neuron(x, w, b):
    p = np.dot(x, w) + b
    y = p > 0
    return np.int64(y)

y = formal_neuron(x, w, b)
print(y)

[[0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]]


## **Example 3.1.6** Implementing Linear class and Step class

In [ ]:
import numpy as np

class Linear:
  #constructor
  def __init__(self, w, b):
    self.w = w
    self.b = b

  #calculate output from input
  def forward(self, x):
    p = np.dot(x, self.w) + self.b
    return p

class Step:
  def forward(self, x):
    y = x > 0
    return np.int64(y)

x = np.array([[0,0,0],
              [0,0,1],
              [0,1,0],
              [0,1,1],
              [1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
w = np.array([[0.5, 0.0],
              [1.0, 0.5],
              [0.5, 1.0]])
b = np.array([-0.5, -1.0])

linear = Linear(w,b)
step = Step()

p = linear.forward(x)
y = step.forward(p)

print(y)

[[0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]]


## 🤔 **Exercise 3.1.3**

In [ ]:
x=[[0,1,1,1],
   [0,1,0,0],
   [1,1,0,0]]
w=[[-2,0,2,2],
   [-1,2,1,-1],
   [4,-3,1,0],
   [1,1,0,-3]]
b= [[-1,0,0,-2]]

linear = Linear(w,b)
step = Step()

p = linear.forward(x)
y = step.forward(p)
print(y)

[[1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]]


## **Example 3.1.7** Implementation of MLP model

In [ ]:
class Linear:
  def __init__(self, w, b):
    self.w = w
    self.b = b

  def forward(self, x):
    p = np.dot(x, self.w) + self.b
    return p

class Step:
  def forward(self, x):
    y = x > 0
    return np.int64(y)

x = np.array([[0,0,0],
              [0,0,1],
              [0,1,0],
              [0,1,1],
              [1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
w = np.array([[0.5, 1.0, 1.0],
              [1.0, 0.5, 0.5],
              [0.5, 1.0, 0.0]])
b = np.array([-0.5, -1.5, -1.0])
u = np.array([[1.0, 0.5],
              [0.5, 0.0],
              [0.0, 1.0]])
c = np.array([-1.0, 0.0])

linear1 = Linear(w,b)
step1 = Step()
linear2 = Linear(u,c)
step2 = Step()

p = linear1.forward(x)
y = step1.forward(p)
q = linear2.forward(y)
z = step2.forward(q)

print(y)
print(z)

## 🤔 **Exercise 3.1.4**

In [ ]:
x=[[1,1,1],
   [0,1,0],
   [1,0,0],
   [1,0,1]]

w= [[-2,1,0,1],
    [0,1,-2,-1],
    [1,0,1,1]]

b=[[-2,1,0,-1]]

u=[[4,1],
   [2,3],
   [0,1],
   [3,1]]

c=[[-2,-4]]

linear1 = Linear(w, b)
step = Step()
linear2 = Linear(u, c)

p = linear1.forward(x)
y = step.forward(p)
q = linear2.forward(y)
z = step.forward(q)

print(y)
print(z)

[[0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 1 1]]
[[0 0]
 [0 0]
 [0 0]
 [1 1]]
