<a href="https://colab.research.google.com/github/GARCIAAA123/Introduction-to-Machine-Learning/blob/main/3_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Machine Learning Chapter 3.3**
# **Multilayer Perceptron with Sigmoid function**
---

## Import libraries

In [ ]:
import numpy as np                  # for scientific computing (e.g. culclations with array)
import matplotlib.pyplot as plt     # for visualization

## 【Note】Dot-product (inner-product) and Hadamard product in Python

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[2,2,2],
              [3,3,3]])

# Hadamard product
print("a * b =\n", a*b)
print()

# T attribute is the transpose of the array. b.T means the transpose of the array b.
print("b.T =\n", b.T)
print()

# Dot-product of a and b.T
print("np.dot(a, b.T) =\n", np.dot(a, b.T))
print()

a * b =
 [[ 2  4  6]
 [12 15 18]]

b.T =
 [[2 3]
 [2 3]
 [2 3]]

np.dot(a, b.T) =
 [[12 18]
 [30 45]]



## **Example** 3.3.1 Linear class and Sigmoid class

In [ ]:
class Linear:
  def __init__(self, w, b):
    self.w = w    # weight
    self.b = b    # bias

  def forward(self, x):
    p = np.dot(x, self.w) + self.b
    return p

class Sigmoid:
  def forward(self, x):
    y = 1 / (1 + np.exp(-x))
    return y

In [ ]:
x = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])
w = np.array([[2],
              [2]])
b = np.array([-3])

# create instances
linear = Linear(w,b)
sigmoid = Sigmoid()


# forward calculation
p = linear.forward(x)
y = sigmoid.forward(p) # Using sigmoid class insted of Step class

# print x (input array) and y (output array)
print("x=\n", x)
print("y=\n", y)

x=
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
y=
 [[0.04742587]
 [0.26894142]
 [0.26894142]
 [0.73105858]]


## 🤔 **Exercise 3.3**

In [ ]:
x = [[1,1,1],
    [0,1,0],
    [1,0,0],
    [1,0,1]]

w = [[-2,1,0,1],
     [0,1,-2,1],
     [1,0,1,1]]

b = [[-2,1,0,-1]]

u =[[4,1],
    [2,3],
    [0,1],
    [3,1]]

c =[[-2,-4]]

# create instances
linear1 = Linear(w, b)
sigmoid = Sigmoid()
linear2 = Linear(u, c)

# forward calculation
p = linear1.forward(x)
y = sigmoid.forward(p)
t = linear.forward(y)
z = sigmoid.forward(t)

# print x (input array) and y (output array)
print("x=\n", x)
print("y=\n", y)

x=
 [[1, 1, 1], [0, 1, 0], [1, 0, 0], [1, 0, 1]]
y=
 [[0.04742587 0.95257413 0.26894142 0.88079708]
 [0.11920292 0.88079708 0.11920292 0.5       ]
 [0.01798621 0.88079708 0.5        0.5       ]
 [0.04742587 0.88079708 0.73105858 0.73105858]]
